name: paperplus
version: '${project.version}'
main: com.github.kumo0621.paperplus.Paperplus
api-version: '1.20'
commands:
  ad:
    aliases: ad
    permission: ad

permissions:
  ad:
    default: true